wandb_version: 1

pretrain:
  desc: null
  value: OpenLLMAI/Llama-2-7b-sft-model-ocra-500k
dataset:
  desc: null
  value: Anthropic/hh-rlhf,tasksource/oasst1_pairwise_rlhf_reward,lmsys/chatbot_arena_conversations,openai/webgpt_comparisons
dataset_probs:
  desc: null
  value: 0.72,0.08,0.12,0.08
save_path:
  desc: null
  value: ./ckpt/7b_llama
save_steps:
  desc: null
  value: -1
logging_steps:
  desc: null
  value: 1
eval_steps:
  desc: null
  value: -1
ckpt_path:
  desc: null
  value: ./ckpt/checkpoints_rm
max_ckpt_num:
  desc: null
  value: 3
max_ckpt_mem:
  desc: null
  value: 1000
max_epochs:
  desc: null
  value: 1
micro_train_batch_size:
  desc: null
  value: 1
train_batch_size:
  desc: null
  value: 128
max_samples:
  desc: null
  value: 1000000
load_checkpoint:
  desc: null
  value: false
max_norm:
  desc: null
  value: 1.0
max_len:
  desc: null
  value: 2048
l2:
  desc: null
  value: 0.0
loss:
  desc: null
  value: sigmoid
gradient_checkpointing:
  desc: null
  value: true
seed:
  desc: null
  value: 42
local_rank:
  desc: null
  value: 0
zero_stage:
  desc: null
  value: 3
bf16:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 9.0e-06
zpg:
  desc: null
  value: 1
adam_offload:
  desc: null
  value: false
flash_attn:
  desc: null
  value: true
compute_fp32_loss:
  desc: null
  value: false
margin_loss:
  desc: null
  value: false
aux_loss_coef:
  desc: null
  value: 0
grad_accum_dtype:
  desc: null
  value: null
disable_trace_cache:
  desc: null
  value: false
load_in_4bit:
  desc: null
  value: false
lora_rank:
  desc: null
  value: 0
lora_alpha:
  desc: null
  value: 16
lora_dropout:
  desc: null
  value: 0
target_modules:
  desc: null
  value: all-linear
gradient_checkpointing_use_reentrant:
  desc: null
  value: false
disable_fast_tokenizer:
  desc: null
  value: false
head_prefix:
  desc: null
  value: value_head
prompt_key:
  desc: null
  value: null
chosen_key:
  desc: null
  value: null
rejected_key:
  desc: null
  value: null
input_template:
  desc: null
  value: 'Human: {}

    Assistant: '
apply_chat_template:
  desc: null
  value: false
tokenizer_chat_template:
  desc: null
  value: null
use_wandb:
  desc: null
  value: 'True'
wandb_org:
  desc: null
  value: esfrankel-uw-org
wandb_group:
  desc: null
  value: train_rm_llama
wandb_project:
  desc: null
  value: openrlhf_train_rm_ppi
wandb_run_name:
  desc: null
  value: rm_0701T16:25
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.41.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719876617
    t:
      1:
      - 1
      - 11
      - 30
      - 49
      - 51
      - 55
      - 71
      - 98
      3:
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.17.2
      6: 4.41.0
      8:
      - 5
      13: linux-x86_64
